
(defpackage #:ftw
  (:use #:cl #:cffi)
  (:export ;; constants.lisp
           #:const
           #:logior-consts

	   ;; ffi.lisp 
           #:switch
           #:with-wide-string
           #:memset
           #:point
           #:wparam
           #:lparam
           #:msg
           #:make-msg
           #:msg-hwnd
           #:msg-message
           #:msg-wparam
           #:msg-lparam
           #:msg-time
           #:msg-pt 
           #:msg-foreign
           #:foreign-msg
           #:get-message
           #:translate-message
           #:dispatch-message
           #:post-quit-message
           #:post-message
           #:send-message
           #:send-message-timeout
           #:register-window-message
           #:get-active-window
           #:defwndproc
           #:get-module-handle
           #:unregister-class 
           #:register-class
           #:create-window
           #:message-box
           #:default-window-proc
           #:show-window
           #:update-window
           #:destroy-window
           #:get-stock-object
           #:get-sys-color-brush
           #:get-sys-color
           #:load-icon
           #:load-cursor
           #:load-image
           #:in-send-message-p
           #:enum-child-windows
           #:find-window
           #:get-parent
           #:make-rect
           #:rect-left
           #:rect-right
           #:rect-top
           #:rect-bottom
           #:rect-foreign
           #:foreign-rect
           #:info
           #:info-size
           #:info-window
           #:info-client
           #:info-style
           #:info-ex-style
           #:info-status
           #:info-borders
           #:info-type
           #:info-version
           #:get-window-info
           #:move-window
           #:set-window-text
           #:set-window-pos
           #:invalidate-rect
           #:paintstruct
           #:paintstruct-hdc
           #:paintstruct-erase
           #:paintstruct-paint
           #:paintstruct-restore
           #:paintstruct-inc-update
           #:paintstruct-foreign
           #:foreign-paintstruct
           #:begin-paint
           #:end-paint
           #:with-paint
           #:draw-caption
           #:draw-focus-rect
           #:draw-edge
           #:redraw-window
           #:text-out
           #:get-client-rect
           #:flash-window
           #:message-beep
           #:client-to-screen
           #:get-window-rect
           #:get-system-metrics
           #:register-hot-key
           #:unregister-hot-key
           #:encode-rgb
           #:decode-rgb
           #:create-solid-brush
           #:create-pen
           #:virtual-key-code
           #:virtual-code-key
           #:create-menu
           #:append-menu
           #:set-menu
           #:create-popup-menu
           #:delete-menu
           #:destroy-menu
           #:track-popup-menu
           #:check-menu-item 
           #:check-menu-radio-item
           #:get-menu-state
           #:init-common-controls
           #:choose-color
           #:get-open-file-name
           #:get-save-file-name
           #:set-background-color
           #:ext-text-out
           #:is-dialog-button-checked
           #:check-dialog-button
           #:select-object
           #:delete-object
           #:set-timer
           #:kill-timer
           #:rectangle
           #:draw-text
           #:set-pixel
           #:move-to
           #:line-to
           #:poly-bezier
           #:create-hatch-brush
           #:create-pattern-brush
           #:create-bitmap
           #:get-window-text-length
           #:get-window-text
           #:with-tool-info
           #:make-long
           #:make-lparam
           #:loword
           #:hiword
           #:nmhdr 
           #:foreign-nmhdr
           #:nmhdr-foreign
           #:updown
           #:foreign-updown
           #:updown-foreign
           #:systemtime
           #:systemtime-year
           #:systemtime-month
           #:systemtime-day-of-week
           #:systemtime-day
           #:systemtime-hour
           #:systemtime-minute
           #:systemtime-second
           #:systemtime-milli
           #:foreign-systemtime
           #:systemtime-foreign
           #:tcitem
           #:tcitem-mask
           #:tcitem-state
           #:tcitem-state-mask
           #:tcitem-text
           #:tcitem-image
           #:tcitem-lparam
           #:foreign-tcitem
           #:tcitem-foreign
           #:create-font
           #:set-bk-mode
           #:set-bk-color 
           #:ext-create-pen
           #:polygon
           #:ellipse
           #:round-rect
           #:chord
           #:polyline
           #:bit-blt
           #:create-compatible-dc
           #:bitmap
           #:bitmap-type
           #:bitmap-width
           #:bitmap-height
           #:bitmap-width-bytes
           #:bitmap-planes
           #:bitmap-bits-per-pixel
           #:bitmap-bits
           #:extlogpen
           #:extlogpen-pen-style
           #:extlogpen-width
           #:extlogpen-brush-style
           #:extlogpen-color
           #:extlogpen-hatch
           #:extlogpen-entries
           #:logfont
           #:logfont-height 
           #:logfont-width
           #:logfont-escapement
           #:logfont-orientation
           #:logfont-weight
           #:logfont-italic
           #:logfont-underline
           #:logfont-strikeout
           #:logfont-charset
           #:logfont-out-precision
           #:logfont-clip-precision
           #:logfont-quality
           #:logfont-pitch-and-family
           #:logfont-name 
           #:get-object
           #:delete-dc
           #:nonclientmetrics
           #:nonclientmetrics-size
           #:nonclientmetrics-border-width
           #:nonclientmetrics-scroll-width
           #:nonclientmetrics-scroll-height
           #:nonclientmetrics-caption-width
           #:nonclientmetrics-caption-height
           #:nonclientmetrics-caption-font
           #:nonclientmetrics-small-caption-width
           #:nonclientmetrics-small-caption-height
           #:nonclientmetrics-small-caption-font
           #:nonclientmetrics-menu-width
           #:nonclientmetrics-menu-height
           #:nonclientmetrics-menu-font
           #:nonclientmetrics-status-font
           #:nonclientmetrics-message-font
           #:nonclientmetrics-padded-border-width
           #:system-parameters-info
	   #:set-focus
	   #:get-focus 
	   #:createstruct
	   #:createstruct-param
	   #:createstruct-instance
	   #:createstruct-menu
	   #:createstruct-parent-hwnd
	   #:createstruct-cy
	   #:createstruct-cx
	   #:createstruct-y
	   #:createstruct-x
	   #:createstruct-styles
	   #:createstruct-name
	   #:createstruct-class-name
	   #:createstruct-ex-styles
	   #:foreign-createstruct
	   #:is-dialog-message
	   #:get-dc 
	   #:release-dc 
	   #:create-dialog 
	   #:dialog-box 
	   #:end-dialog
	   #:enable-window 
	   #:get-class-info
	   #:wndclassex
	   #:wndclassex-size
	   #:wndclassex-style
	   #:wndclassex-wndproc
	   #:wndclassex-class-extra
	   #:wndclassex-wnd-extra
	   #:wndclassex-instance
	   #:wndclassex-icon
	   #:wndclassex-cursor
	   #:wndclassex-brush
	   #:wndclassex-menu-name
	   #:wndclassex-class-name
	   #:wndclassex-icon-small
	   #:default-dialog-proc
	   #:is-window
	   
	   ;; ftw.lisp 
	   #:set-default-font 
	   
           ))
           
           

